### PR TITLE
Add Updatecli

### PR DESCRIPTION
**Pull request by tracymiranda**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by tracymiranda** [comment]
@AndreyKozlov1984 the deploy logs no longer seem to show the error messages - do you know why? This issue is probably svg related but need the logs to know for sure...

**Comment by olblak** [comment]
Can I be of any assistance here?

**Comment by tracymiranda** [comment]
think it may be a logo issue but will rebase first and get this back to building first... bear with me..

**Comment by olblak** [comment]
This pullrequest can be closed as I recreated another one on https://github.com/ossf/ossf-landscape/pull/362

**Comment by olblak** [comment]
Thanks @tracymiranda for opening this one initially.
This open pullrequest motivated me to fix the svg logo

**Pull request closed without merging**
