### PR TITLE
Add Knative to the sigstore landscape.

### PR DESCRIPTION
**Pull request by mattmoor**
Knative started signing in 1.8 (although some images were missed), they expect this to complete in 1.9 (ETA January), but given that some of the release images are signed I think they count!

Signed-off-by: Matt Moore <mattmoor@chainguard.dev>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by mattmoor** [comment]
@vaikas LMK if there's a better logo to include here.

**Comment by mattmoor** [comment]
whoops, I added the PNG 🙃

**Comment by upodroid** [comment]
There is an svg logo at https://github.com/cncf/artwork/blob/master/projects/knative/icon/color/knative-icon-color.svg

🎉 🎉 🎉

**Comment by mattmoor** [comment]
preview LGTM

cc @tracymiranda

**Comment by tracymiranda** [comment]
Woohoo, welcome Knative! Thanks all!

**Pull request merged**
