### PR TITLE
Re-enable auto updating of members

### PR DESCRIPTION
**Pull request by jmertic**
@hythloda Please review and make sure the member logo list is correct. Thanks!

### CODE REVIEW

**Comment by hythloda** [comment]
well we have a new issue that "White Source Ltd., d.b.a mend.i" doesn't like their given name and want to be called just "mend.io"  I made the changes in LFX. But will that propagate down the pipeline?

**Comment by hythloda** [comment]
> well we have a new issue that "White Source Ltd., d.b.a mend.i" doesn't like their given name and want to be called just "mend.io" I made the changes in LFX. But will that propagate down the pipeline? They are watching the landscape pretty closely right now since they just annouced.

Mend is not in the right spot :(

**Comment by jmertic** [comment]
Hi! I can keep trying through the day to see when the API updates. So far, it's showing the old name.

I see mend.io is a 'General' member, and it shows for me in that section; not sure if you are referring to something else..

**Comment by jmertic** [comment]
Got it - yeah that would be corrected once the right company name is
populated.

**Comment by jmertic** [comment]
@hythloda ok - this should be better now; can you double-check the build and make sure there is nothing else that is wrong?

**Comment by hythloda** [comment]
LGTM

**Review by hythloda — APPROVED** [review]

**Pull request merged**
