### PR TITLE
Add several missing projects from the landscape.

### PR DESCRIPTION
**Pull request by mattmoor**
LinkerD, Shipwright, and Keptn all appear to be missing.

Signed-off-by: Matt Moore <mattmoor@chainguard.dev>

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by mattmoor** [comment]
I just see a spinning thing in the logs here: 
image

I wonder if the table needs another resize since I'm adding so many things.  It could also be that I omitted crunchbase for Shipwright/Keptn which I could not find them for.

**Comment by mattmoor** [comment]
cc @tracymiranda (not a rush)

**Comment by tracymiranda** [comment]
Thanks for this pr @mattmoor 
Not sure why the logs weren't showing but yeah will fall over without crunchbase info. Hope you don't mind, I added that in, also updated logo names and removed how to verify info as was not adding new info (and it's not a required field).

**Comment by mattmoor** [comment]
@tracymiranda thanks for the changes, that's totally cool! 🙏

**Comment by mattmoor** [comment]
The render LGTM 🙏

**Pull request merged**
